### ISSUE TITLE
VMs not translated

### ISSUE THREAD

**Issue by elBelgg** [scolcipitato/folder.view#19]
Trying to delete a folder in VMs tab doesnt translate the confirmation text.

Docker confirmation:
![image](https://github.com/user-attachments/assets/e0bc41ad-af0f-47f9-8669-46b27add79e3)

VMs confirmation:
![image](https://github.com/user-attachments/assets/004b3be9-be3b-44ff-a32a-08c0183efd6e)

**Comment by scolcipitato** [comment]
Fixed in [b223e39](https://github.com/scolcipitato/folder.view/commit/b223e39a991e39ce4fe4274b80ba85e174a17ff3)
